# This is a basic workflow to help you get started with Actions

name: Auto Update Stats Images

# Controls when the action will run. Triggers the workflow on auto-scheduled push events
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:

    # Sleep for 5 minutes before building
    - name: Sleep for 5 mins
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'

    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Run using Python 3.10 for consistency and aiohttp
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    # Cache dependencies. From:
    # https://github.com/actions/cache/blob/master/examples.md#python---pip
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Switch to actions_branch if not exist, or create new actions_branch
    - name: Switch to actions_branch
      run: |
        git checkout actions_branch 2>/dev/null || git checkout -b actions_branch
        git pull origin actions_branch

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 git_stats_imgs.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: ${{ secrets.EXCLUDE_FORKED_REPOS }}
        REPO_VIEWS: ${{ secrets.REPO_VIEWS }}
        LAST_VIEWED: ${{ secrets.LAST_VIEWED }}
        FIRST_VIEWED: ${{ secrets.FIRST_VIEWED }}
        MAINTAIN_REPO_VIEWS: ${{ secrets.MAINTAIN_REPO_VIEWS }}
        REPO_CLONES: ${{ secrets.REPO_CLONES }}
        LAST_CLONED: ${{ secrets.LAST_CLONED }}
        FIRST_CLONED: ${{ secrets.FIRST_CLONED }}
        MAINTAIN_REPO_CLONES: ${{ secrets.MAINTAIN_REPO_CLONES }}
        MORE_COLLABS: ${{ secrets.MORE_COLLABS }}

    # Commits all changed files to the repository
    - name: Commit to the repo
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Auto Update GitHub stats images' || echo
        git push origin actions_branch
